import "./globals.css";
// import "@repo/ui/styles.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <Navbar />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
